name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4
      - name: Add plugin and install
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          asdf plugin add superdb "$GITHUB_WORKSPACE"
          asdf install superdb latest
          super --version
